# yaml-language-server: $schema=https://activate.parallel.works/workflow.schema.json

permissions:
  - '*'

sessions:
  session:
    useTLS: false
    redirect: true
    useCustomDomain: false
    prompt-for-name:
        default: hpcmp_status
'on':
  execute:
    inputs: {}

jobs:
  run_status_tracker:
    steps:
      - name: Run in user workspace
        run: |
          set -e
          # install deps and start
          ./run_dashboard.sh
  create_session:
    steps:
      - name: Wait for Server To Start
        early-cancel: any-job-failed
        env:
          host: localhost
          port: "8080"
        retry:
          interval: 3s
          max-retries: 1000
          timeout: 5s
        run: curl --fail --silent "http://${host}:${port}" >/dev/null 2>&1
      - name: Update Session
        uses: parallelworks/update-session
        with:
          remotePort: 8080
          name: ${{ sessions.session }}
          status: 'running'
          target: 'user-workspace'
